import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const roblox = resolve(root, "roblox");

function luaString(source: string): string {
  let equals = "";
  while (source.includes(`]${equals}]`)) equals += "=";
  return `[${equals}[${source}]${equals}]`;
}

const [config, server, client] = await Promise.all([
  readFile(resolve(roblox, "SessionTrackerConfig.example.lua"), "utf8"),
  readFile(resolve(roblox, "SessionTracker.server.lua"), "utf8"),
  readFile(resolve(roblox, "SessionTracker.client.lua"), "utf8"),
]);

const installer = `-- Generated by npm run roblox:installer.
-- Paste this entire file into Roblox Studio's Command Bar and press Enter.
local ServerScriptService = game:GetService("ServerScriptService")
local StarterPlayerScripts = game:GetService("StarterPlayer"):WaitForChild("StarterPlayerScripts")

local function install(parent, className, name, source, preserveExisting)
\tlocal existing = parent:FindFirstChild(name)
\tif existing and not existing:IsA(className) then
\t\texisting:Destroy()
\t\texisting = nil
\tend
\tif existing and preserveExisting then
\t\tprint("SessionTracker preserved existing " .. existing:GetFullName())
\t\treturn existing
\tend
\tlocal instance = existing or Instance.new(className)
\tinstance.Name = name
\tinstance.Source = source
\tinstance.Parent = parent
\tprint("SessionTracker installed " .. instance:GetFullName())
\treturn instance
end

install(ServerScriptService, "ModuleScript", "SessionTrackerConfig", ${luaString(config)}, true)
install(ServerScriptService, "Script", "SessionTracker", ${luaString(server)}, false)
install(StarterPlayerScripts, "LocalScript", "SessionTracker", ${luaString(client)}, false)

print("SessionTracker installation complete. Configure ServerScriptService.SessionTrackerConfig before publishing.")
`;

await writeFile(resolve(roblox, "Install.lua"), installer, "utf8");
console.log("Generated roblox/Install.lua");

